### ISSUE TITLE
Directory instance in container run methods

### ISSUE THREAD

**Issue by dhodovsk** [fedora-modularity/conu#81]
Add directory parameter to run methods (instance of Directory) - it is automatically mounted to container at start

**Comment by jscotka** [comment]
This should be solved also for __port__ forwardinf.
as there is in `container run` commands like in class `DockerRunCommand`
is allows pass `additional_opts=` list inside that there can be used transformations like:

otherwise Directory class should allow directory mapping maybe as optional param otherwise for example /tmp will be used what the allows to use it to mountind dirs into container

```
self.additional_args = []
for opt in additional_opts:
    if opt isinstance(opt, Directory):
        ...
        self.additional_args.append(...)
    elif opt isinstance(opt, PortForwarding):
       ...
        self.additional_args.append(...)
     else:
        self.additional_args.append(opt)    
```

**Comment by TomasTomecek** [comment]
@jscotka sounds reasonable, I agree with you. Except only on the "fallback to `/tmp`" part. My opinion is that it should be explicit.

**Comment by TomasTomecek** [comment]
Quick brainstorm:
```python
def run_via_*(volumes=[(Directory(), "/mountpoint", "Z")])
```
First and 3rd arg are optional.
Even simpler form:
```python
def run_via_*(volumes=(Directory(), "/mountpoint", "Z"))
```
or
```python
def run_via_*(volumes=("/var/lib", "/mountpoint", "Z"))
```

This is just a brainstorm, please advise better implementation.
